openapi: 3.0.0
info:
  title: Webshop API
  version: 1.0.0
paths:
  /api/users/login:
    post:
      summary: Benutzer anmelden
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Anmeldung erfolgreich
        '401':
          description: Ungültige Anmeldeinformationen

  /api/users/register:
    post:
      summary: Benutzer registrieren
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
      responses:
        '201':
          description: Registrierung erfolgreich
        '400':
          description: Registrierung fehlgeschlagen

  /api/users/reset-password:
    post:
      summary: Passwort zurücksetzen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Passwort zurückgesetzt
        '404':
          description: Benutzer nicht gefunden
        '500':
          description: Interner Serverfehler

  /api/products:
    get:
      summary: Produkte im Katalog anzeigen
      responses:
        '200':
          description: Liste von Produkten
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    image:
                      type: string
                      format: url
                    name:
                      type: string
                    weight:
                      type: number
                    price:
                      type: number
      # Hier könnten Sie auch Sicherheits- und Berechtigungsanforderungen hinzufügen

  /api/cart/add:
    post:
      summary: Produkt zum Warenkorb hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
      responses:
        '201':
          description: Produkt wurde zum Warenkorb hinzugefügt
        '400':
          description: Schlechte Anfrage - Ungültige Eingabe
        '404':
          description: Produkt nicht gefunden
        '500':
          description: Interner Serverfehler
          
  /api/cart:
    get:
      summary: Warenkorb anzeigen
      responses:
        '200':
          description: Warenkorb anzeigen
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: integer
                        name:
                          type: string
                        price:
                          type: number
                        weight:
                          type: number
                        quantity:
                          type: integer
                  total_price:
                    type: number
                  # Weitere mögliche Felder für die Anzeige des Warenkorbs

  /api/cart/order:
    post:
      summary: Bestellung aufgeben
      responses:
        '201':
          description: Bestellung aufgegeben
        '400':
          description: Schlechte Anfrage - Ungültige Eingabe
        '500':
          description: Interner Serverfehler